- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 10800 # 3 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 28800 # 8 hours
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
    underwearb: ClothingUnderwearBottomBoxersCap # Sirena-Underwear
  underweart: ClothingUnderwearTopBraCap # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesCap # Sirena-Underwear
  innerclothingskirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
